---
- name: Install sudo on ArchLinux
  pacman:
    name: sudo
    state: present
  when: ansible_os_family == 'Archlinux'

- name: Install sudo on RedHat
  yum:
    name: sudo
    state: present
  when: ansible_os_family == 'RedHat'

- name: Configure sudoers
  copy:
    dest: /etc/sudoers
    src: sudoers
    validate: 'visudo -cf %s'
