---
- name: Create groups
  group:
    name: '{{ item.name }}'
    system: '{{ (item.system is defined and item.system)|bool }}'
    state: present
  when: baseline_groups is defined
  with_items: baseline_groups

- name: Create users without ancillary groups
  user:
    name: '{{ item.username }}'
    password: '{{ item.password }}'
    group: '{{ item.group }}'
    system: '{{ (item.system is defined and item.system)|bool }}'
    state: present
  when: baseline_users is defined and item.groups is not defined
  with_items: baseline_users

- name: Create users with ancillary groups
  user:
    name: '{{ item.username }}'
    password: '{{ item.password }}'
    group: '{{ item.group }}'
    groups: '{{ item.groups|join(",") }}'
    append: yes
    system: '{{ (item.system is defined and item.system)|bool }}'
    state: present
  when: baseline_users is defined and item.groups is defined
  with_items: baseline_users

- name: Set authorized_keys for users with public keys
  authorized_key:
    user: '{{ item.username }}'
    key: '{{ lookup("file", "public_keys/" + item.username + ".pub") }}'
    key_options: '{{ item.pubkey_options|default(omit) }}'
  when: baseline_users is defined and item.pubkey is defined and item.pubkey
  with_items: baseline_users
