---
- name: Install docker
  yum:
    name: docker
    state: present

- name: Enable and start docker
  service:
    name: docker
    enabled: yes
    state: started

- name: Install docker python library for ansible
  pip:
    name: docker-py
    version: 1.1.0

- name: Add docker group
  group:
    name: docker
    system: yes
    state: present

- name: Add users to docker group
  user:
    name: '{{ item }}'
    groups: docker
    append: yes
    state: present
  with_items:
    - confman
    - '{{ admin_user }}'
  notify: restart docker
