---
ansible_ssh_host: 192.168.1.250

baseline_networking:
  hostname: '{{ inventory_hostname }}.jleight.com'
  adapters:
    - adapter: eno16777984
      address: 192.168.1.250
      netmask: 24
      gateway: 192.168.1.1
      nameservers:
        - 8.8.8.8
        - 8.8.4.4

firewall_config:
  open_tcp:
    - port: 22

docker_run:
  - nginx
  - sabnzbd
  - sickbeard
